Repository SyzygyStation/Syzygy-Eris, pull requests merged in 2020-11, with the labels that each got.

#225 reduced spawn rate for disks. From 8.5 to 7
  zzz_modular_syzygy/code/modules/loot_spawn_blacklist.dm
Labels: Balance/Rebalance

#224 Nerfed Autolathe recycling
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/smelter.dm
  zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Labels: Balance/Rebalance

#223 pricing adjustments
  zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Labels: Balance/Rebalance

#222 adds several fun things and loadout items
  cev_eris.dme
  code/__DEFINES/items_clothing.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  zzz_modular_syzygy/code/game/objects/items/toys/balls.dm
  zzz_modular_syzygy/code/game/objects/items/toys/costume.dm
  zzz_modular_syzygy/code/game/objects/items/toys/laserpointer.dm
  zzz_modular_syzygy/code/modules/loadout/lists/eyegear.dm
  zzz_modular_syzygy/code/modules/loadout/lists/headwear.dm
  zzz_modular_syzygy/code/modules/loadout/lists/misc.dm
  zzz_modular_syzygy/code/modules/loadout/lists/suits.dm
  zzz_modular_syzygy/code/modules/loadout/lists/uniforms.dm
  zzz_modular_syzygy/icons/mob/toys_l.dmi
  zzz_modular_syzygy/icons/mob/toys_mouth.dmi
  zzz_modular_syzygy/icons/mob/toys_r.dmi
  zzz_modular_syzygy/icons/obj/toys.dmi
Labels: Enhancement, Feature

#220 Oops! all bank card descriptions
  zzz_modular_syzygy/code/game/jobs/SZdepartment.dm
Labels: Bugfix

#219 Ports Polaris Translators, fixes SolCom listing
  cev_eris.dme
  code/modules/mob/language/station.dm
  zzz_modular_syzygy/icons/obj/translators.dmi
  zzz_modular_syzygy/translators.dm
Labels: Feature, Sprites

#226 More Church Updates
  code/datums/setup_option/core_implants.dm
  code/game/objects/items/complicator.dm
  code/game/objects/items/devices/last_shelter.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/vat.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Balance/Rebalance, Quality of Life, Upstream update

#227 Update price_list_fixed.dm
  zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Labels: Bugfix

#228 Underwears Galore!
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirt.dm
  icons/inventory/underwear/mob.dmi
Labels: Enhancement, Sprites

#229 Cherry picks an optimization PR from upstream
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/monkey.dm
  code/modules/sanity/sanity_mob.dm
Labels: Optimization / Modularization, Upstream update

#230 Fixes Galore!
  code/game/atoms.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  code/modules/economy/cash.dm
  code/modules/economy/price_list.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/mech_life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/multiz/structures.dm
  code/modules/multiz/turf.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy/nt_svalinn.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/guns/projectile/pistol/colt.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
Labels: Balance/Rebalance, Bugfix, Feature, Upstream update

#232 Sofa Port
  cev_eris.dme
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  zzz_modular_syzygy/icons/obj/sofas.dmi
  zzz_modular_syzygy/sofas.dm
Labels: Feature, Sprites

#237 fixed Trauma Control System nanites from not repairing internal organs
  code/modules/reagents/reagents/nanites.dm
Labels: Bugfix

#238 Remove References to non-lore compliant organization
  cev_eris.dme
  code/__DEFINES/items.dm
  zzz_modular_syzygy/code/game/objects/items/NZR.dm
Labels: Lore compliance

#239 Defib Timer Tweaks, Spawnpoint Bugfixes
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/security.dm
  zzz_modular_syzygy/defib.dm
Labels: Bugfix
