Repository SyzygyStation/Syzygy-Eris, pull requests merged in 2020-09, with the labels that each got.

#90 Cherry-pick Eris updates no.2
  cev_eris.dme
  code/__HELPERS/game.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/datums/craft/menu.dm
  code/datums/perks/oddity.dm
  code/game/jobs/job/job.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/hologram.dm
  code/game/machinery/multistructure.dm
  code/game/machinery/shower.dm
  code/game/objects/effects/chem/chemsmoke.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/circuitboards/machinery/mining_drill.dm
  code/game/objects/items/weapons/implant/implants/carrion/toxic_spider.dm
  code/game/objects/items/weapons/material/thrown.dm
  code/game/sound.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/client/preference_setup/augmentation/01_modifications.dm
  code/modules/mining/drilling/brace.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/say.dm
  code/modules/modular_computers/file_system/programs/engineering/shield_control.dm
  code/modules/organs/external/damage.dm
  code/modules/organs/external/stump.dm
  code/modules/organs/organ.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/random_map/noise/ore.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents/toxins.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/scrap/scrap.dm
  code/modules/shield_generators/shield_generator.dm
  code/modules/virus2/helpers.dm
Labels: Bugfix, Enhancement, Feature, Upstream update

#92 Bandaid Patch for Spawning Without A Cruciform
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix, Feature, Squash-merge

#94 Fixes Traitor Uplink Exploitable Information
  nano/templates/uplink.tmpl
Labels: Bugfix, Feature

#95 Fix null-related runtimes
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/turfs/simulated/floor_icon.dm
  code/modules/modular_computers/hardware/scanners/scanner_reagent.dm
Labels: Bugfix, Enhancement

#96 Improve joint-locking feedback
  code/modules/mob/mob_grab_specials.dm
Labels: Bugfix, Enhancement, Feature

#93 adds syzygy specific flavor fixes to muh deepmaint rooms
  maps/submaps/deepmaint_rooms/normal/oopsitsbeartraps.dmm
  maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
Labels: Enhancement, Lore compliance, Mapping

#99 Fixes Gunnery Sergeant Loadout.
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
Labels: Lore compliance, Squash-merge

#102 Cherry-pick Eris updates no.3
  code/controllers/subsystems/jobs.dm
  code/datums/autolathe/biomatter.dm
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/computer_parts.dm
  code/datums/autolathe/guns.dm
  code/datums/autolathe/security.dm
  code/datums/datacore.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/recharger.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/research.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/implant/implants/carrion/breeding_spider.dm
  code/game/objects/items/weapons/implant/implants/carrion/control_spider.dm
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/modules/admin/topic.dm
  code/modules/clothing/spacesuits/captain.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/detectivework/tools/rag.dm
  code/modules/mechs/mech_construction.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  code/modules/organs/internal/carrion.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasma.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/bluespace.dm
  code/modules/telesci/bcrystal.dm
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
  icons/obj/guns/energy/laser.dmi
  icons/obj/guns/energy/martyr.dmi
  icons/obj/power_cells.dmi
  nano/templates/sanity.tmpl
Labels: Upstream update

#104 Cherry-pick Eris updates no.4
  cev_eris.dme
  code/__DEFINES/components.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/logging.dm
  code/controllers/subsystems/garbage.dm
  code/datums/objective/merc_mission.dm
  code/datums/objective/steal.dm
  code/datums/perks/job.dm
  code/game/jobs/job/captain.dm
  code/game/objects/items/complicator.dm
  code/game/objects/items/devices/last_shelter.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/devices/von-krabin.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/maneki_neko.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/atomic_distillery.dm
  code/modules/reagents/enricher.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  icons/obj/oddities.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Upstream update

#105 Fix some DNA shit
  code/game/dna/dna2.dm
Labels: Bugfix, Enhancement, Quality of Life

#108 Buff amount of biomatter per sheet
  code/modules/biomatter_manipulation/solidifier.dm
Labels: Balance/Rebalance, Enhancement

#109 Soulcrypt hold stats & remove harpoons from traitors and loot pools.
  code/datums/contract.dm
  code/datums/uplink/devices and tools.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/stashes/stash_types/captain.dm
Labels: Balance/Rebalance, Bugfix, Enhancement

#116 Minor Hivemind Nerf
  code/game/gamemodes/events/hivemind_invasion.dm
  zzz_modular_syzygy/hugbox.dm
Labels: Balance/Rebalance, Enhancement

#115 Adds Stinger Grenades and Rubbershot Shells
  cev_eris.dme
  code/game/machinery/vending_eclipse.dm
  zzz_modular_syzygy/ammo.dm
  zzz_modular_syzygy/grenades.dm
  zzz_modular_syzygy/icons/ammo.dmi
  zzz_modular_syzygy/icons/grenades.dmi
  zzz_modular_syzygy/projectiles.dm
Labels: Enhancement, Feature

#113 Adds Yoga Pants
  cev_eris.dme
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/mob/uniform.dmi
  zzz_modular_syzygy/icons/mob/uniform_fem.dmi
  zzz_modular_syzygy/icons/uniform_icons.dmi
  zzz_modular_syzygy/loadout.dm
Labels: Bugfix, Enhancement, Feature

#114 AED Unit and Defib Belt update!
  cev_eris.dme
  code/controllers/configuration.dm
  icons/inventory/belt/mob.dmi
  sound/effects/genetics.ogg
  sound/machines/defib_SafetyOn.ogg
  sound/machines/defib_charge.ogg
  sound/machines/defib_failed.ogg
  sound/machines/defib_overchargeSparks1.ogg
  sound/machines/defib_overchargeSparks2.ogg
  sound/machines/defib_overchargeWarning.ogg
  sound/machines/defib_overchargeZap.ogg
  sound/machines/defib_ready.ogg
  sound/machines/defib_safetyOff.ogg
  sound/machines/defib_success.ogg
  sound/machines/defib_zap.ogg
  zzz_modular_syzygy/_helpers.dm
  zzz_modular_syzygy/defib.dm
  zzz_modular_syzygy/defiblocker.dm
  zzz_modular_syzygy/icons/mob/back.dmi
  zzz_modular_syzygy/icons/mob/belt.dmi
  zzz_modular_syzygy/icons/mob/left_hand.dmi
  zzz_modular_syzygy/icons/mob/right_hand.dmi
  zzz_modular_syzygy/icons/mob/wielded.dmi
  zzz_modular_syzygy/icons/obj/ErisDefib.dmi
Labels: Feature

#117 Make taurs show up properly in space suits
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Enhancement

#118 Ports new markings from virgo
  code/modules/sprite_accessories/extra.dm
  code/modules/sprite_accessories/sprite_accessories_vr.dm
  icons/mob/human_races/markings_vr.dmi
  icons/mob/vore/ears_vr.dmi
  icons/mob/vore/tails_vr.dmi
Labels: Enhancement, Sprites

#120 Removed some Moebius mentions I missed.
  code/game/jobs/job/medical.dm
Labels: Lore compliance

#119 Maps a defib cabinet into the medical office
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes

#125 Added new Prefixes.
  code/modules/mob/living/carbon/human/human.dm
Labels: Enhancement

#121 adds the Mentor storyteller
  cev_eris.dme
  zzz_modular_syzygy/storytellers/mentor.dm
Labels: Enhancement

#124 Yoga Pants Patch
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/mob/uniform.dmi
  zzz_modular_syzygy/icons/mob/uniform_fem.dmi
  zzz_modular_syzygy/icons/uniform_icons.dmi
Labels: Enhancement, Sprites

#123 Cherry picks new Extinguisher sprites from upstream
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/structures/extinguisher.dm
  code/modules/mechs/equipment/utility.dm
  icons/obj/closet.dmi
  icons/obj/items.dmi
Labels: Enhancement, Upstream update

#122 Ports Upstream Mech Improvements
  cev_eris.dme
  code/datums/autolathe/devices.dm
  code/datums/craft/recipes/misc.dm
  code/game/objects/items/devices/floor_painter.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/modules/cargo/packs.dm
  code/modules/mechs/components/armour.dm
  code/modules/mechs/components/arms.dm
  code/modules/mechs/components/body.dm
  code/modules/mechs/components/frame.dm
  code/modules/mechs/components/head.dm
  code/modules/mechs/components/legs.dm
  code/modules/mechs/components/software.dm
  code/modules/mechs/equipment/utility.dm
  code/modules/mechs/interface/datum_HUD.dm
  code/modules/mechs/interface/screen_objects.dm
  code/modules/mechs/mech.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/mech_movement.dm
  code/modules/mechs/premade/_premade.dm
  code/modules/mechs/premade/combat.dm
  code/modules/mechs/premade/heavy.dm
  code/modules/mechs/premade/light.dm
  code/modules/mechs/premade/misc.dm
  code/modules/mechs/premade/powerloader.dm
  code/modules/research/designs/mechs2/exosuits_components.dm
  code/modules/research/nodes/robotics.dm
  icons/mechs/mech_hud.dmi
  icons/obj/bureaucracy.dmi
  icons/obj/weapons.dmi
  nano/css/shared.css
  nano/images/science.png
Labels: Enhancement, Upstream update

#129 Buckshot Can Now Splatter Roachpiles
  code/modules/projectiles/projectile/bullets.dm
  html/changelogs/Crosarius-Buckshot.yml
Labels: Balance/Rebalance

#130 adds captains coat and associated sprotes
  cev_eris.dme
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/mob/suit.dmi
  zzz_modular_syzygy/icons/mob/suit_fem.dmi
  zzz_modular_syzygy/icons/suit_icons.dmi
  zzz_modular_syzygy/lockers.dm
Labels: Enhancement

#132 [CHERRY PICK] Removes a mob spawner from one of the One Star dungeon rooms (#5424)
  maps/submaps/dungeon_rooms/rooms/armory_secure.dmm
Labels: Administrative

#128 Update mentor.dm
  zzz_modular_syzygy/storytellers/mentor.dm
Labels: Enhancement

#133 Oddity storage changes to make some easier to have on your person
  code/game/objects/items/oddities.dm
  code/modules/clothing/clothing.dm
Labels: Quality of Life

#134 Captain's Wardrobe Update
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/mob/uniform.dmi
  zzz_modular_syzygy/icons/mob/uniform_fem.dmi
  zzz_modular_syzygy/icons/suit_icons.dmi
  zzz_modular_syzygy/icons/uniform_icons.dmi
  zzz_modular_syzygy/lockers.dm
Labels: Enhancement, Sprites

#135 Captainvoidsuit
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/head_icons.dmi
  zzz_modular_syzygy/icons/mob/head.dmi
  zzz_modular_syzygy/icons/mob/suit.dmi
  zzz_modular_syzygy/icons/mob/suit_fem.dmi
  zzz_modular_syzygy/icons/suit_icons.dmi
Labels: Enhancement, Sprites

#143 armour actually works now pogchamp
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Bugfix

#141 Captain's Voidsuit
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_syzygy/cargoexports.dm
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/icons/mob/head.dmi
  zzz_modular_syzygy/icons/mob/suit.dmi
  zzz_modular_syzygy/icons/mob/suit_fem.dmi
  zzz_modular_syzygy/stashes.dm
Labels: Enhancement, Map Changes, Sprites

#142 Stash Coordinate Fix
  code/modules/stashes/stash_datum.dm
Labels: Enhancement

#137 adds medical bay and bathroom to centcomm.dmm
  maps/CEVEris/centcomm.dmm
Labels: Map Changes

#138 Slight changes to Unathi
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Balance/Rebalance

#144 Roach Knockdown Tweak
  cev_eris.dme
  code/modules/mob/living/carbon/superior_animal/roach/attack.dm
  zzz_modular_syzygy/roach.dm
Labels: Balance/Rebalance

#150 Species blurb updates on character creation menu to better reflect our own lore.
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
Labels: Lore compliance

#149 More items for the tubular pouch to hold.
  cev_eris.dme
  zzz_modular_syzygy/pouches.dm
Labels: Balance/Rebalance, Quality of Life

#148 changes steady receipe
  code/modules/reagents/recipes.dm
Labels: Balance/Rebalance, Quality of Life

#147 Doubles the duration of the round-end phase
  code/controllers/subsystems/ticker.dm
Labels: Enhancement

#145 Trap-style awareness for wire splicing.
  cev_eris.dme
  zzz_modular_syzygy/wire_splicing.dm
Labels: Quality of Life

#139 Sanity_mob.DM edits
  code/modules/sanity/sanity_mob.dm
Labels: Bugfix, Ready for review

#152 Added audio feedback to pulling atoms. Properly modularized.
  code/modules/mob/living/living.dm
Labels: Enhancement

#154 Maps in more AED cabinets
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes

#155 Adds a minimum crew requirement for Hivemind and Blob
  cev_eris.dme
  zzz_modular_syzygy/storytellers/events.dm
Labels: Balance/Rebalance

#158 Makes the Energy Armblade Implant stop despawning itself (#5485)
  code/game/objects/items/weapons/melee/energy.dm
Labels: Bugfix, Ready for review, Upstream update

#156 Kaiser iconstate fix
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
Labels: Bugfix, Squash-merge

#153 Added pixel-shifting with cntl+shift+movement keys
  cev_eris.dme
  code/datums/movement/mob.dm
  interface/skin.dmf
  zzz_modular_syzygy/pixelshift.dm
Labels: Feature

#151 Implements crew transfer votes
  cev_eris.dme
  code/controllers/subsystems/ticker.dm
  zzz_modular_syzygy/vote.dm
Labels: Feature

#165 new storyteller: the Lookout
  cev_eris.dme
  zzz_modular_syzygy/storytellers/lookout.dm
Labels: Feature

#160 marshals are now freelance bounty hunters
  code/game/antagonist/station/marshal.dm
Labels: Balance/Rebalance

#161 Disables Hivemind Teleport
  code/modules/hivemind/machines.dm
  code/modules/hivemind/self_defense.dm
Labels: Balance/Rebalance

#166 Command Armoury Buff
  cev_eris.dme
  code/modules/projectiles/guns/energy/plasma.dm
  icons/obj/guns/energy/brigador.dmi
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_syzygy/plasma.dm
Labels: Map Changes

#167 Recolours Captain's Wardrobe
  zzz_modular_syzygy/icons/head_icons.dmi
  zzz_modular_syzygy/icons/mob/head.dmi
  zzz_modular_syzygy/icons/mob/suit.dmi
  zzz_modular_syzygy/icons/mob/suit_fem.dmi
  zzz_modular_syzygy/icons/mob/uniform.dmi
  zzz_modular_syzygy/icons/mob/uniform_fem.dmi
  zzz_modular_syzygy/icons/suit_icons.dmi
  zzz_modular_syzygy/icons/uniform_icons.dmi
Labels: Sprites
