Repository SyzygyStation/Syzygy-Eris, pull requests merged in 2020-08, with the labels that each got.

#1 Include autodoc machinery to the game
  .travis.yml
  cev_eris.dme
  code/game/machinery/autodoc.dm
  code/game/objects/items/weapons/circuitboards/machinery/medical.dm
Labels: enhancement

#5 Fix Holodeck plane layering issue
  code/__HELPERS/unsorted.dm
Labels: bugfix

#6 Nuke hunger slowdown out of existence
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: enhancement

#7 Increase overall limit of languages; 2 -> 3
  code/modules/client/preference_setup/background/02_language.dm
Labels: enhancement

#8 Change overcoats to storage subtypes
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/weapons/storage/deferred.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/stashes/stash_types/captain.dm
Labels: enhancement, refactor

#9 Clean-up unused languages and bloat
  code/__DEFINES/species_languages.dm
  code/datums/perks/job.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
Labels: refactor, squash-merge

#10 Gloves now always protect against scrap cutting
  code/modules/scrap/scrap.dm
Labels: enhancement

#11 Add security gloves to lockers & loadout selection
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
Labels: enhancement

#12 Give Moebius RD access to AI Private channel
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
Labels: enhancement, squash-merge

#13 Add ventcrawl to all drones
  code/_onclick/cyborg.dm
  code/modules/mob/living/silicon/robot/drone/_drone.dm
Labels: bugfix, enhancement

#14 Adjust respawn delays & fix observer warning
  code/__DEFINES/mobs.dm
  code/modules/mob/new_player/new_player.dm
Labels: bugfix, enhancement

#15 Buff drones' item pull size
  code/modules/mob/living/silicon/robot/drone/_drone.dm
Labels: enhancement

#16 Autoinjector Alterations
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: enhancement

#17 Add Brig access to Aegis Medical Specialist
  code/game/jobs/job/security.dm
Labels: enhancement

#18 Renames Chemist job to Pharmacist
  code/datums/outfits/jobs/medical.dm
  code/game/jobs/job/medical.dm
Labels: enhancement, refactor

#19 Add flare to survival boxes
  code/game/objects/items/weapons/storage/boxes.dm
Labels: enhancement

#20 Update Eris' nanoUI map images
  nano/images/eris/eris-1.png
  nano/images/eris/eris-2.png
  nano/images/eris/eris-3.png
  nano/images/eris/eris-4.png
  nano/images/eris/eris-5.png
Labels: enhancement

#21 New autoinjector boxes
  code/game/objects/items/weapons/storage/boxes.dm
Labels: enhancement

#35 Fix Virgo & alien hair styles
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  code/modules/sprite_accessories/extra.dm
  icons/mob/human_races/species/human/hair.dmi
Labels: bugfix, enhancement, sprites, squash-merge

#36 Fix multi-z falling and catwalks
  code/game/objects/structures/catwalk.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/multiz/turf.dm
Labels: bugfix

#32 Adjusts in-game tips to fit our lore.
  code/modules/tips_and_tricks/jobs.dm
Labels: Bugfix, Enhancement, Lore compliance, Squash-merge

#49 Make MC error states & soft-resetting more verbose
  code/controllers/master.dm
Labels: Enhancement

#48 Reduces lobby music volume
  code/datums/lobbyscreen.dm
Labels: Enhancement

#51 Cherrypick changes from NEV-Eclipse no.1
  code/game/jobs/job/church.dm
  code/game/objects/items/oddities.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/modules/engineering.dm
  icons/obj/faction_item.dmi
  icons/obj/kitchen.dmi
  icons/obj/neotheology_machinery.dmi
  icons/obj/soulcrypt.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Enhancement, Feature, Lore related, Refactor, Upstream update

#61 Replaced mentions of Eclipse Discord.
  code/game/jobs/whitelist.dm
  code/game/verbs/ooc.dm
Labels: Administrative

#65 Vendors fix
  code/game/machinery/vending.dm
  code/game/machinery/vending_eclipse.dm
Labels: Balance/Rebalance, Enhancement

#66 Fix preferences-related runtimes
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Bugfix, Squash-merge

#67 Refactor alt-click handling of vent-crawling
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/modules/ventcrawl/ventcrawl.dm
Labels: Bugfix, Enhancement, Refactor

#68 Fix "gulp down" always succeeding when it should not
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Bugfix

#81 Fix runtime caused by gravity generator
  code/modules/power/gravitygenerator.dm
Labels: Bugfix

#83 Patch a leak over medical cloning room
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix

#84 Updated in game years.
  code/global.dm
  code/modules/economy/economy_misc.dm
  code/modules/games/spaceball_cards.dm
Labels: Lore compliance
