Repository SyzygyStation/Syzygy-Eris, pull requests merged in 2020-10, with the labels that each got.

#168 Ported several citadel/skyrat/tg sprites for use on Syzygy
  cev_eris.dme
  zzz_modular_syzygy/_accessories_sprite.dm
  zzz_modular_syzygy/_accessory_hair.dm
  zzz_modular_syzygy/icons/mob/jamini-ears.dmi
  zzz_modular_syzygy/icons/mob/jamini-hair.dmi
  zzz_modular_syzygy/icons/mob/jamini-markings.dmi
  zzz_modular_syzygy/icons/mob/jamini-tails.dmi
  zzz_modular_syzygy/icons/mob/jamini-taurs.dmi
Labels: Sprites

#170 Mining fixes and Tweaks
  code/modules/mining/drilling/drill.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore_datum.dm
  icons/obj/mining.dmi
  icons/obj/structures.dmi
Labels: Balance/Rebalance, Bugfix, Quality of Life

#164 Oddity Changes pass #2
  zzz_modular_syzygy/oddities.dm
Labels: Optimization / Modularization

#171 Adminhelps get sent to deadmins, if there are no admins online
  code/__HELPERS/global_lists.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/adminhelp.dm
Labels: Administrative

#172 Atomized Bugfix - Captain's Greatcoat
  zzz_modular_syzygy/icons/mob/suit.dmi
Labels: Bugfix, Sprites

#173 Hands are hands, not arms
  code/modules/mob/living/carbon/carbon.dm
Labels: Bugfix, Enhancement, Hand and foot code

#174 Cherry picks a ton of stuff from upstream
  cev_eris.dme
  code/__DEFINES/items_clothing.dm
  code/__DEFINES/research.dm
  code/__DEFINES/tools_and_qualities.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/mindswapper.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/circuitboards/machinery/mindswapper.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  code/modules/projectiles/guns/mods/mods.dm
  code/modules/research/designs.dm
  code/modules/research/designs/gunmods.dm
  code/modules/research/designs/toolmods.dm
  code/modules/research/nodes/biotech.dm
  code/modules/research/nodes/combat.dm
  code/modules/research/nodes/engineering.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/obj/machines/research.dmi
  icons/obj/tool_upgrades.dmi
  nano/css/shared.css
  nano/images/science.png
Labels: Upstream update

#175 Map fixes and more!
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes, Priority: High

#176 Adds a surplus gun mods crate
  cev_eris.dme
  zzz_modular_syzygy/crates.dm
Labels: Feature

#177 changes frozen star vendor messages in vending.dm
  code/game/machinery/vending.dm
  zzz_modular_syzygy/storytellers/lookout.dm
Labels: Lore compliance

#179 Lever Action Shotgun
  cev_eris.dme
  code/game/objects/random/lathe_disks.dm
  zzz_modular_syzygy/icons/levergun.dmi
  zzz_modular_syzygy/icons/sawnlevergun.dmi
  zzz_modular_syzygy/levergun.dm
  zzz_modular_syzygy/lockers.dm
  zzz_modular_syzygy/sawnlevergun.dm
Labels: Feature, Sprites

#180 Giant spider naming
  cev_eris.dme
  zzz_modular_syzygy/giant_spider.dm
Labels: Enhancement

#178 A massive fluster cluck of bugfixes and QoL improvements from upstream
  code/datums/autolathe/guns.dm
  code/datums/craft/step.dm
  code/datums/datacore.dm
  code/datums/topic/admin.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/trays.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/medical_stand.dm
  code/modules/admin/admin.dm
  code/modules/admin/map_capture.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/ghosttrap/trap.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mob/inventory/equip.dm
  code/modules/mob/living/carbon/brain/posibrain.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/organs/internal/eyes.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/random_map/drop/supply.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/stashes/stash_types/excelsior.dm
  code/modules/tables/presets.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/items/lefthand_uniforms.dmi
  icons/mob/items/righthand_uniforms.dmi
  interface/interface.dm
  interface/skin.dmf
Labels: Bugfix, Optimization / Modularization, Priority: High, Quality of Life, Upstream update

#182 Cherry picking batch: Bluespace Storage items and Tasers-don't-ignore-armor
  code/datums/helper_datums/teleport.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/power/singularity/act.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs.dm
  code/modules/research/nodes/bluespace.dm
  icons/inventory/belt/icon.dmi
  icons/inventory/belt/mob.dmi
  icons/inventory/pockets/icon.dmi
  icons/obj/janitor.dmi
  icons/obj/mining.dmi
  icons/obj/storage/backpack.dmi
Labels: Balance/Rebalance, Feature, Upstream update

#185 Economy Tweaks
  cev_eris.dme
  code/modules/economy/price_list.dm
  zzz_modular_syzygy/code/game/jobs/SZdepartment.dm
  zzz_modular_syzygy/code/modules/economy/price_list_fixed.dm
Labels: Balance/Rebalance, Bugfix, Enhancement

#183 Medspec can has shades
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
Labels: Quality of Life

#181 Actually gives access to acolytes and preachers, and make soulcrypts show up on medical scanners
  code/game/jobs/job/church.dm
  code/game/machinery/adv_med.dm
Labels: Bugfix, Enhancement, Priority: High, Quality of Life

#169 Adds a vote to magically power the ship
  zzz_modular_syzygy/vote.dm
Labels: Quality of Life

#186 Fixes icon regression, retires obsolete overrides and typepaths
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/inventory/belt/mob.dmi
  icons/inventory/face/icon.dmi
  icons/inventory/face/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Bugfix, Priority: High, Sprites, Upstream update

#188 Yet Another Batch of Cherry Picked PRs for New Features, Bugfixes and QoL Improvements
  code/controllers/configuration.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/global.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/mob/inventory/equip.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/multiz/map_data.dm
  code/modules/overmap/sectors.dm
  code/modules/power/lighting.dm
  config/example/config.txt
  interface/interface.dm
  interface/skin.dmf
  maps/CEVEris/overmap-eris.dm
  maps/encounters/asteroid/asteroid.dm
Labels: Bugfix, Enhancement, Quality of Life, Upstream update

#191 haha vector go brrrrrt
  cev_eris.dme
  zzz_modular_syzygy/icons/vector.dmi
  zzz_modular_syzygy/vector.dm
Labels: Feature

#184 Quality of Life Improvements for Roleplayers and more
  cev_eris.dme
  code/__DEFINES/misc.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/mob/say.dm
  interface/interface.dm
  interface/skin.dmf
  zzz_modular_syzygy/multiline_me.dm
Labels: Administrative, Feature, Quality of Life

#187 few* map changes
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes

#194 Fixes Aloe mixing
  zzz_modular_syzygy/code/modules/reagents/recipes.dm
Labels: Bugfix, Quality of Life

#195 Hotfix for CMO and Virology access being messed up
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Map Changes, Priority: High

#199 Random Bugfixes
  code/game/objects/items/weapons/tools/_tools.dm
  code/modules/clothing/masks/miscellaneous.dm
Labels: Bugfix, Priority: High, Runtime, Upstream update

#198 Hotfix: Non-hotkeymode will now be playable
  interface/interface.dm
  interface/skin.dmf
Labels: Bugfix, Priority: High

#202 Added many markings
  cev_eris.dme
  zzz_modular_syzygy/code/modules/sprite_accessories/_accessories_sprite.dm
  zzz_modular_syzygy/code/modules/sprite_accessories/_accessory_hair.dm
  zzz_modular_syzygy/icons/mob/jamini-markings.dmi
Labels: Enhancement, Sprites

#204 Fixes some fancy spawning stuff and cargo chute
  cev_eris.dme
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_syzygy/code/modules/loot_spawn_blacklist.dm
Labels: Bugfix, Enhancement, Map Changes, Ready for review

#205 The Tier 0 Eris Med Port
  cev_eris.dme
  code/__DEFINES/damage_organs.dm
  code/datums/craft/recipes/misc.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners/health.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/internal/_internal.dm
  code/modules/organs/internal/bones.dm
  code/modules/organs/organ_description.dm
  code/modules/surgery/internal.dm
  code/modules/surgery/organic.dm
  code/modules/surgery/organic_damage.dm
  code/modules/surgery/surgery_ui.dm
  code/modules/virus2/effect.dm
  icons/obj/surgery.dmi
  nano/templates/surgery_organ.tmpl
Labels: Feature, Hand and foot code, Upstream update

#200 Feedback Implementation, Phase 1
  code/modules/clothing/masks/miscellaneous.dm
  zzz_modular_syzygy/clothing.dm
  zzz_modular_syzygy/sawnlevergun.dm
Labels: Balance/Rebalance, Bugfix

#206 Members of The Church can now augment their bodies.
  code/datums/setup_option/core_implants.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/organs/body_modifications.dm
Labels: Lore compliance, Lore related, Quality of Life

#211 Randomizes the License point value for oldified disks.
  cev_eris.dme
  code/modules/scrap/oldificator.dm
  zzz_modular_syzygy/code/modules/scrap/oldificator.dm
Labels: Balance/Rebalance

#207 Fixes not being able to implant implants in core implanted people with implanters.
  code/game/objects/items/weapons/implant/implants/excelsior.dm
  code/modules/core_implant/core_implant.dm
Labels: Enhancement

#209 Reduced tool durability and added oldification effects to tools and weapons
  cev_eris.dme
  code/game/objects/items/weapons/tools/_tools.dm
  zzz_modular_syzygy/code/game/objects/items/tools/_tools.dm
  zzz_modular_syzygy/code/modules/scrap/oldificator.dm
Labels: Balance/Rebalance

#213 Fixes EFTPOS not displaying names for department accounts
  code/modules/economy/economy_misc.dm
  zzz_modular_syzygy/code/game/jobs/SZdepartment.dm
Labels: Bugfix, Enhancement, Quality of Life

#210 Gun Tagging Fix
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic/atreides.dm
  code/modules/projectiles/guns/projectile/automatic/c20r.dm
  code/modules/projectiles/guns/projectile/automatic/drozd.dm
  code/modules/projectiles/guns/projectile/automatic/maxim.dm
  code/modules/projectiles/guns/projectile/automatic/molly.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/handmade.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/revolver/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Bugfix, Upstream update

#208 Loads more blacklisting
  zzz_modular_syzygy/code/modules/loot_spawn_blacklist.dm
Labels: Balance/Rebalance

#216 Cleaning fixes
  cev_eris.dme
  code/modules/reagents/reagents/other.dm
  zzz_modular_syzygy/code/game/objects/effects/decals/Cleanable/humans.dm
Labels: Bugfix, Priority: High

#215 Church Update Port
  cev_eris.dme
  code/__DEFINES/jobs.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystems/jobs.dm
  code/datums/outfits/jobs/church.dm
  code/datums/perks/job.dm
  code/datums/setup_option/core_implant.dm
  code/datums/setup_option/core_implants.dm
  code/game/dna/dna2.dm
  code/game/dna/dna2_helpers.dm
  code/game/jobs/access.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/last_shelter.dm
  code/modules/client/preference_setup/augmentation/01_modifications.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/machinery/vat.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/body_modifications.dm
  code/modules/organs/organ_description.dm
  code/modules/projectiles/guns/projectile/revolver/sky_driver.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/soulcrypt/_overwrites.dm
  code/modules/soulcrypt/access_update_tool.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/debug.dm
  code/modules/soulcrypt/helpers.dm
  code/modules/soulcrypt/holochip.dm
  code/modules/soulcrypt/module.dm
  icons/obj/machines/church_vat.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Bugfix, Feature, Upstream update

#212 Fluster Cluck Port: Eris Prosthesis, take 2
  cev_eris.dme
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/organs/external/subtypes/robotic_types.dm
  icons/inventory/uniform/mob_fem.dmi
  icons/mob/human_races/cyberlimbs/advanced_ghetto.dmi
  icons/mob/human_races/cyberlimbs/asters.dmi
  icons/mob/human_races/cyberlimbs/claw_arm.dmi
  icons/mob/human_races/cyberlimbs/excelsior.dmi
  icons/mob/human_races/cyberlimbs/frozen_star.dmi
  icons/mob/human_races/cyberlimbs/ghetto.dmi
  icons/mob/human_races/cyberlimbs/moebius.dmi
  icons/mob/human_races/cyberlimbs/one_star.dmi
  icons/mob/human_races/cyberlimbs/serbian.dmi
  icons/mob/human_races/cyberlimbs/spike_arm.dmi
  icons/mob/human_races/cyberlimbs/tank_leg.dmi
  icons/mob/human_races/cyberlimbs/technomancer.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/advanced_ghetto.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/asters.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/claw_arm.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/excelsior.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/frozen_star.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/generic.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/ghetto.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/moebius.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/neotheology.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/one_star.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/serbian.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/spike_arm.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/tank_leg.dmi
  zzz_modular_syzygy/icons/eris_prosthesis/technomancer.dmi
  zzz_modular_syzygy/prosthesis/implementation.dm
  zzz_modular_syzygy/prosthesis/prosthesis_brands.dm
  zzz_modular_syzygy/prosthesis/prosthesis_parts.dm
Labels: Hand and foot code, Sprites, Upstream update

#201 Defibrillator Touchup Patch
  zzz_modular_syzygy/defib.dm
Labels: Bugfix, Quality of Life

#217 Church patch port
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/vat.dm
  code/modules/core_implant/cruciform/rituals/group.dm
  icons/obj/neotheology_machinery.dmi
Labels: Quality of Life, Ready for review, Upstream update

#218 adds quick cash option to ATM
  cev_eris.dme
  zzz_modular_syzygy/code/modules/economy/ATM.dm
Labels: Quality of Life
